#!/usr/bin/env python3
"""Convert the supplied event artwork to a 300px native RGB565 LVGL asset."""
from pathlib import Path
from PIL import Image
import hashlib
root = Path(__file__).resolve().parents[1]
ui = root / 'firmware/factory_badge/main/ui'
source = ui / 'assets/developers-after-dark.png'
im = Image.open(source).convert('RGB').resize((300, 300), Image.Resampling.LANCZOS)
data = bytearray()
for r, g, b in im.getdata():
    value = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
    data.extend((value & 255, value >> 8))
(ui / 'invitation_art.h').write_text('#pragma once\n#include <lvgl.h>\nnamespace badge::ui { extern const lv_image_dsc_t invitation_art; }\n')
lines = ['// Supplied artwork; generated by scripts/generate-invitation-art.py.',
         '// Source SHA-256: ' + hashlib.sha256(source.read_bytes()).hexdigest(),
         '#include "invitation_art.h"', 'namespace badge::ui {',
         'alignas(4) static const uint8_t pixels[] = {']
lines += [','.join(str(v) for v in data[i:i+32]) + ',' for i in range(0,len(data),32)]
lines += ['};', '''const lv_image_dsc_t invitation_art = [] {
    lv_image_dsc_t image{};
    image.header.magic = LV_IMAGE_HEADER_MAGIC;
    image.header.cf = LV_COLOR_FORMAT_RGB565;
    image.header.w = 300; image.header.h = 300; image.header.stride = 600;
    image.data_size = sizeof(pixels); image.data = pixels;
    return image;
}();
}''']
(ui / 'invitation_art.cpp').write_text('\n'.join(lines)+'\n')
